### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms#33]
There is almost no documentation or even code comments to explain what the code does. For example, I'm trying to use `c_execute_tri_lo2hi` but there is no explanation what basis the lo should be in.

**Comment by dlfivefifty** [comment]
I managed to reverse-engineer it:
```julia


julia> P = c_plan_rottriangle(5, 0.,0.,0.);

julia> F = zeros(5,5); F[1,2] = 1; F
5×5 Array{Float64,2}:
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

julia> c_execute_tri_hi2lo(P, F); F
5×5 Array{Float64,2}:
 0.0   0.942809  0.0  0.0  0.0
 0.0  -0.333333  0.0  0.0  0.0
 0.0   0.0       0.0  0.0  0.0
 0.0   0.0       0.0  0.0  0.0
 0.0   0.0       0.0  0.0  0.0

julia> m,ℓ = 1,0;  Fun(t -> Fun(NormalizedJacobi(0,2m+1,0..1),[zeros(ℓ);1])(t) * 2^m*(1-t)^m, NormalizedJacobi(0,1,0..1))
Fun(NormalizedJacobi(0.0,1.0,0..1),[0.942809, -0.333333])
```

**Comment by MikaelSlevinsky** [comment]
I'm weighing all the different options for documentation such as: LaTeX, github.io, or the Wiki. LaTeX is good because it's lightweight (when the PDF isn't committed), but this may bloat the repository in time. Using GitHub.io is neat, but it will never look as good as what `Documenter.jl` produces for Julia packages. The automation behind the way it strips help text from package functions is great.

Maybe the best option is the wiki? It allows GitHub's flavour of markdown, which in turn allows html and thereby LaTeX for math. I don't think it add commits to the repository itself.

**Comment by MikaelSlevinsky** [comment]
Actually, looks like GitHub's markdown strips away scripts, so MathJax is probably off the table.

**Comment by dlfivefifty** [comment]
The wiki is a bad idea, it’s hard to edit and it’s better to use something inside the version control.

**Comment by MikaelSlevinsky** [comment]
I might hold off for a bit. Nothing's settled at this point. For example, the signature of the computational kernel `ft_kernel_tri_hi2lo` may change to specify the hi and lo `m` values, not just assuming `m` down to `0`. Let me know if there's anything that needs urgent explaining.

**Comment by MikaelSlevinsky** [comment]
What do you think? http://mikaelslevinsky.github.io/FastTransforms/ The mobile use chops some of the formulas off, but perhaps that will be fixed in time

**Comment by MikaelSlevinsky** [comment]
Now that the structure is there, more documentation can be added
